# Generated by Django 4.2.14 on 2024-07-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_reply_created_alter_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replies', to='board.reply'),
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.reply')),
            ],
        ),
    ]
